### ISSUE TITLE
Doesn't work on Windows

### ISSUE THREAD

**Issue by nilgoyette** [noshu/lbfgs-sys#2]
I installed gfortran from mingw, added the binary folder to my PATH and tried to compile this project.

```
error: failed to run custom build command for `lbfgsb-sys v0.1.0 (C:\Imeka\lbfgsb-sys)`
process didn't exit successfully: `C:\Imeka\lbfgsb-sys\target\debug\build\lbfgsb-sys-f76ce81dffa63f64\build-script-build` (exit code: 101)
--- stdout
Running: "mingw32-make" "dylib" "OUTPUT=C:/Imeka/lbfgsb-sys/target/debug/build/lbfgsb-sys-3705fb3a64faf030/out" "OSNAME=Windows"

--- stderr
Makefile:29: *** missing separator.  Stop.
thread 'main' panicked at '`"mingw32-make" "dylib" "OUTPUT=C:/Imeka/lbfgsb-sys/target/debug/build/lbfgsb-sys-3705fb3a64faf030/out" "OSNAME=Windows"` failed: exit code: 2', build.rs:37:13
```

The problem is that there are 4 spaces instead of one tab at line 29.

**Comment by nilgoyette** [comment]
Hey, thank you for merging @fmorency branch. Sadly you missed one [commit](https://github.com/imeka/lbfgsb-sys/commit/ebe0c21bf7d92348352e5a9ef50306d212cd49fb) (a fix for WSL). With this, we will be able to use your lib again, and crates.io if you publish your changes.

Btw  @noshu do you plan to work on this lib or at least read the issues and PR? If not, could you please add someone as the maintainer? Three persons have forked this project and contributed: @fmorency, @nilgoyette or @jturner314 (disclaimer: I didn't ask for his opinion).

**Comment by noshu** [comment]
Hey @nilgoyette thanks for your response. Currently i have no plan to work on this library. I created this repo to use it with my rustimization library. Further more i have another repo which is the rust binding of conjugate gradient descent algorithm. If you want, i can make you  and the other two the maintainer of these three repositories.

**Comment by nilgoyette** [comment]
We (fmorency and I) don't have much plan either, but we do want to answer issues and PR when they arise, so I'll accept the maintainer role. Don't add the others, I'll add them myself if need be.
